# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  ### Urchin Keyboard
  # Urchin dongle (Raytac USB-A)
  - board: raytac_mdbt50q_rx
    shield: urchin_dongle
    cmake-args: -DCONFIG_ZMK_DISPLAY=n -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: urchin_dongle-mdbt50q_rx
  # Urchin
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view # default nice_view shield
    #shield: urchin_left nice_view_adapter nice_view_gem # default urchin shield (gem)
    #shield: urchin_left nice_view_adapter nice_view_custom # ulounge shield (urchin)
    # Enable ZMK Studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    # With dongle
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_left-central
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view # default nice_view shield
    # With dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_left-peripheral
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter  nice_view # default nice_view shield
    #shield: urchin_right nice_view_adapter  nice_view_gem # default urchin shield (gem)
    #shield: urchin_right nice_view_adapter nice_view_custom # ulounge shield (urchin)
    # With dongle
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_right-peripheral
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset-nice_nano_v2

  ### Forager Keyboard
  # Forager dongle (Raytac MDBT50-RX)
  - board: raytac_mdbt50q_rx
    shield: forager_dongle
    #snippet: studio-rpc-usb-uart # FIXME
    artifact-name: forager_dongle-mdbt50q_rx
  - board: raytac_mdbt50q_rx
    shield: settings_reset
    artifact-name: settings_reset-mdbt50q_rx
  # Forager dongle (Raytac MDBT50-CX-40)
  - board: raytac_mdbt50q_cx_40
    shield: forager_dongle
    #snippet: studio-rpc-usb-uart # FIXME
    artifact-name: forager_dongle-mdbt50q_cx
  - board: raytac_mdbt50q_cx_40
    shield: settings_reset
    artifact-name: settings_reset-mdbt50q_cx
  # Forager dongle (Prospector)
  - board: seeeduino_xiao_ble
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: forager_dongle-prospector
  # Forager
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: forager_left-central
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: forager_left-peripheral
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: forager_right-peripheral
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-xiao_ble
