# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Urchin
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter  nice_view # default nice_view shield
    #shield: urchin_left nice_view_adapter  nice_view_gem # default urchin shield (gem)
    #shield: urchin_left nice_view_adapter nice_view_custom # ulounge shield (urchin)
    # Enable ZMK Studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter  nice_view # default nice_view shield
    #shield: urchin_right nice_view_adapter  nice_view_gem # default urchin shield (gem)
    #shield: urchin_right nice_view_adapter nice_view_custom # ulounge shield (urchin)
  # Forager
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
