# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Urchin dongle (Raytac USB-A)
  - board: raytac_mdbt50q_rx
    shield: urchin_dongle
  # Urchin
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter  nice_view # default nice_view shield
    #shield: urchin_left nice_view_adapter  nice_view_gem # default urchin shield (gem)
    #shield: urchin_left nice_view_adapter nice_view_custom # ulounge shield (urchin)
    # Enable ZMK Studio
    #snippet: studio-rpc-usb-uart
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
    # With dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter  nice_view # default nice_view shield
    #shield: urchin_right nice_view_adapter  nice_view_gem # default urchin shield (gem)
    #shield: urchin_right nice_view_adapter nice_view_custom # ulounge shield (urchin)
    # With dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: settings_reset
  # Forager dongle (Raytac)
  - board: raytac_mdbt50q_rx
    shield: forager_dongle
    #snippet: studio-rpc-usb-uart # FIXME
  - board: raytac_mdbt50q_rx
    shield: settings_reset
  # Forager dongle (Prospector)
  - board: seeeduino_xiao_ble
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
  # Forager
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    #snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: settings_reset
