manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # bravekarma
    - name: caksoylar
      url-base: https://github.com/caksoylar
      # kyek / duckyb
    - name: duckyb
      url-base: https://github.com/duckyb
      # OPTIONAL nice-view-gem (gem animation)
    - name: m165437
      url-base: https://github.com/M165437
    # OPTIONAL nice-view ulounge (urchin animation)
    #- name: ulounge
    #url-base: https://github.com/ulounge
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: urchin-zmk-module
      remote: duckyb
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
    #- name: nice-view-mod
    #remote: ulounge
    #revision: main
  self:
    path: config
